name = "Cashworks"
author = "SeriousFreezing"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11930ba18ca3f496bbbd9d181914a5d32efd82b2ef12c44b41ffefba8cd79470"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
