name = "Minecraft 1.20.1 with NeoForge"
author = "SeriousFreezing"
version = "1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "950864826bee666cc29b950167b7d019767ba7dff212082519c64a6a5e830c82"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
