name = "Cashworks"
author = "SeriousFreezing"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "477354ee13f971c8c84f8fdff4418dfae0dac2f1731df15a67cce61f5acc3b25"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
