name = "Cashworks"
author = "SeriousFreezing"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "165695b87444f9e9041054621ad41f7cdbee2da124ad0f03ddba6c1b53480191"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
