name = "Cashworks"
author = "SeriousFreezing"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a23ef362dfe1d9a2c77a22b6ab2346cb0a5149b11926637c9fb09818d030ce59"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
