name = "Cashworks"
author = "SeriousFreezing"
version = "1.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b2c93560c8dfbfd10857aca160bf6b7aada47466d2cf8e8f63753a7ca0c2f28"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
