name = "Cashworks"
author = "SeriousFreezing"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ebd0b6b8b100d88d0d19c9d77eb163f7948140470221c2bc687d9f64560e6ac"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
