name = "Cashworks"
author = "SeriousFreezing"
version = "1.8.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79964197dceb3f4a1a6526efc337485537afa98508134381a62561d0fa304320"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
