name = "Cashworks"
author = "SeriousFreezing"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f83fc98da3782d5a709f6c5b5011aea6d54a001bf9b365e64cdf64334b6321ba"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
