recipes:
  generateLowQualityGems: false
  hardIronRecipes: false
  hardGlassRecipes: false
  nerfPaperCrafting: false
  harderCharcoalRecipe: false
  flintAndSteelRequireSteel: false
  removeVanillaTNTRecipe: false

worldgen:
  oreVeins:
    removeVanillaOreGen: false
    removeVanillaLargeOreVeins: false