name = "Cashworks"
author = "SeriousFreezing"
version = "1.0.0-neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d07a8e86abfc787b9f28e5e263449960438f88247fa6e82ad97611e9e7500e91"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
